server:
  port: 8085

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tnt_db_master
    username: mdzahidraza
    password: zahid
    platform: postgresql
    initialize: true
    continue-on-error: true

#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tnt_db_master?createDatabaseIfNotExist=true
#    username: root
#    password: zahid
#    platform: mysql
  jpa:
    show-sql: true
    format-sql: true
#    generate-ddl: true
    hibernate:
      ddl-auto: update

security:
  filter-order: 0
  oauth2:
    resource:
      id: TEST_RESOURCE
      filter-order: 3
    client:
      client1:
        access-token-validity: 3600
        refresh-token-validity: 7200
        id: client
        secret: secret
        scope: read,write,trust
