server:
  port: 8085

spring:
  datasource:
    ###### PostgreSQL Configuration #######
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/tnt_db_master
#    username: mdzahidraza
#    password: zahid
#    platform: postgresql
#    initialize: true
#    continue-on-error: true
    #####  MySQL Configuration #######
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tnt_db_master?createDatabaseIfNotExist=true
    username: root
    password: zahid
    platform: mysql
    initialize: true
    continue-on-error: true
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: none
#    properties:
#      org:
#        hibernate:
#          envers:
#            audit_table_suffix: _history


security:
  filter-order: 0
  oauth2:
    resource:
      id: TEST_RESOURCE
      filter-order: 3
    client:
      client1:
        access-token-validity: 3600
        refresh-token-validity: 7200
        id: client
        secret: secret
        scope: read,write,trust

endpoints:
  auditevents:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false



#        spring.jpa.properties.org.hibernate.envers.audit_table_suffix=app_audit
