export const NAV_ACTIVATE = 'NAV_ACTIVATE';

export const USER_ROLE = {
  ROLE_ADMIN: "ADMIN",
  ROLE_USER: "USER"
};

export const USER_TYPE = {
  MERCHANDISING: "MERCHANDISING",
  SAMPLING: "SAMPLING",
  FACTORY: "FACTORY"
};


export const MISC_CONSTANTS = {
  INITIALIZE_TEAM: 'INITIALIZE_TEAM',
  INITIALIZE_PROBLEM: 'INITIALIZE_PROBLEM',
  INITIALIZE_BUYER: 'INITIALIZE_BUYER',
  INITIALIZE_SECTION: 'INITIALIZE_SECTION',
  INITIALIZE_DEPARTMENT: 'INITIALIZE_DEPARTMENT',
  INITIALIZE_PROBLM: 'INITIALIZE_PROBLM',
  INITIALIZE_DESGN: 'INITIALIZE_DESGN',
  STORE_INITIALIZED: 'STORE_INITIALIZED'
};

export const USER_CONSTANTS = {
  INITIALIZE_USER: 'INITIALIZE_USER',
  USER_SYNC_SUCCESS: 'USER_SYNC_SUCCESS',
  USER_SYNC_FAIL: 'USER_SYNC_FAIL',
  USER_AUTH_PROGRESS: 'USER_AUTH_PROGRESS',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAIL: 'USER_AUTH_FAIL',
  USER_BAD_REQUEST: 'USER_BAD_REQUEST',
  USER_ADD_FORM_TOGGLE: 'USER_ADD_FORM_TOGGLE',
  USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
  USER_ADD_FAIL: 'USER_ADD_FAIL',
  USER_EDIT_FORM_TOGGLE: 'USER_EDIT_FORM_TOGGLE',
  USER_EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
  USER_EDIT_FAIL: 'USER_EDIT_FAIL',
  USER_REMOVE_PROGRESS: 'USER_REMOVE_PROGRESS',
  USER_REMOVE_SUCCESS: 'USER_REMOVE_SUCCESS',
  USER_REMOVE_FAIL: 'USER_REMOVE_FAIL',
  USER_FILTER: 'USER_FILTER',
  USER_SORT: 'USER_SORT',
  USER_CHANGE_PASSWD: 'USER_CHANGE_PASSWD',
  USER_BUSY: 'USER_BUSY',
  USER_SEARCH_SUCCESS: 'USER_SEARCH_SUCCESS',
  USER_SEARCH_FAIL: 'USER_SEARCH_FAIL'
};
